### ISSUE TITLE
Device List: remove "badge" style from non-danger badges.

### ISSUE THREAD

**Issue by anthonywittig** [anthonywittig/mLock#14]
I think we should kill the badges for the non-danger badges, here's what it looks like with the non-danger badge:

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/12345527/188260088-a53d84de-d87a-4324-a139-419088ff8501.png">

Here's what it looks like if I break the class on the spans:

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/12345527/188260167-82c43cf0-45d1-4627-8754-f8b51bd1ed1c.png">

Which I think looks a little more uniform with the rest of the page.

I don't think it looks bad when it's next to the danger badges either:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/12345527/188260185-b7f3d4f5-ab93-4b87-9abe-2d5120aadc5a.png">

**Comment by Thryphore** [comment]
![image](https://user-images.githubusercontent.com/54916525/190521540-b3d04cfd-5f5c-4c08-aed6-314673b730f7.png)
I must've done this on #17...

**Comment by anthonywittig** [comment]
Are you saying that screenshot is what's currently in `main`? If so, I think that looks good.
