### ISSUE TITLE
Device List: use bootstrap lists

### ISSUE THREAD

**Issue by anthonywittig** [anthonywittig/mLock#15]
I think we should use the bootstrap list styles everywhere we're using lists. See the [docs](https://getbootstrap.com/docs/4.0/components/list-group/) for more info. We're using react-bootstrap which has some components already defined [here](https://react-bootstrap.github.io/components/list-group/).

I wonder if we should kill off the danger badge and use the `list-group-item-danger`. 🤔 If we did that, we'd probably want to always use a list, even if there's only one item. Something to consider.

**Comment by Thryphore** [comment]
![image](https://user-images.githubusercontent.com/54916525/190707571-8cd8598b-ae92-4dbb-8321-d389eaf183df.png)
Is this indent okay? Tried to get rid of it but it doesn't want to go away...

**Comment by anthonywittig** [comment]
What do you think about making the single items into lists too?

**Comment by Thryphore** [comment]
https://github.com/anthonywittig/mLock/pull/20/commits/6eeb72c7c3eccfbc01d52dd6efa81bded0386019

**Comment by anthonywittig** [comment]
https://github.com/anthonywittig/mLock/pull/20 didn't merge, let's leave these issues open until the issue has been fixed (committed to `main`).

**Comment by Thryphore** [comment]
https://github.com/anthonywittig/mLock/pull/37
