### ISSUE TITLE
Align text on device list page.

### ISSUE THREAD

**Issue by anthonywittig** [anthonywittig/mLock#18]
Can you make it so that the text all aligns (see the gap at the bottom of this for `Status`, `Battery`, and `Unit`):

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/12345527/189808411-ac6bdd37-6d1e-47c2-b77b-369133fb4eb5.png">

It could be nice to make the units a link to the unit detail page (that might make units line up).

**Comment by Thryphore** [comment]
https://github.com/anthonywittig/mLock/pull/19

**Comment by Thryphore** [comment]
I did it here in #19 
![image](https://user-images.githubusercontent.com/54916525/190526672-cfd2a8b3-32e9-43c4-a1ab-017a22f06465.png)

**Comment by anthonywittig** [comment]
I left some feedback on https://github.com/anthonywittig/mLock/pull/19, but you may not have seen it.

**Comment by Thryphore** [comment]
https://github.com/anthonywittig/mLock/pull/37

**Comment by anthonywittig** [comment]
I think there are still some alignment issues:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/12345527/200599949-bfb6d746-0f19-4c68-bf22-b115c4f8753c.png">

**Comment by anthonywittig** [comment]
Looks good!
