### ISSUE TITLE
Add prettier to the project.

### ISSUE THREAD

**Issue by anthonywittig** [anthonywittig/mLock#27]
https://prettier.io/

We'd want this to run with the build and yell at us when our code isn't pretty.

**Comment by anthonywittig** [comment]
We'd want this to run before we build the project (`build.sh`). You'd likely want to add a `format` script to `frontend/package.json`. If we don't like the default config (or if it conflicts with our eslint rules) we'd need to:

* update eslint to agree or
* add a prettierrc file

**Comment by Thryphore** [comment]
https://github.com/anthonywittig/mLock/pull/39
