### ISSUE TITLE
Migrate to the new Google Identity Services library

### ISSUE THREAD

**Issue by anthonywittig** [anthonywittig/mLock#49]
> After March 31, 2023, migration to [Google Identity Services](https://notifications.google.com/g/p/APdRdFxwi8X9pK0GBRFh6uQJdsWFSYzAgE-x-jrt6KtN7Q1s7VXWpYjTqE4r68Qk8YIpueaH1H7t7KQ4e8-PTbNvg492Xx2nUn-JPYqbZ4I_mDLl0HlWFShGqS-jXc4SxGx-xTMt64IBON-sK1b1_FyA-reZOsBmFeOVZmec3SffJ2MsThPhPu8Mps7u0sv55Ig7D69ufboH8QP4S8nqvS6pZwJdl6JtuvR7R1oQoC4kA82hp96V_BACUSItB6CQqdbPhaLgXCIrpi6uIbD1-Xo) is recommended to sign in customers using their Google Account to your platform. The SDK will use the new [Sign in with Google client library](https://notifications.google.com/g/p/APdRdFyeBgm69a2zWS2L2yv_1lta-nEkN3AkU2rwQHPO5ETjTCuW0mBB-jb4dJoK3-_QVgXgDjQtECGQK7ZIxC9xvS1MDW1pGJ-B80J3pOOVASQn-z1KzzFVkOBrr0GhDhVolnimc7HX4K8T9Vyq4xl3pAflaYACS1Qt90XlcJADbB19BsaMO_I2XzmQpwCb_VAO9f91gHQXKQODQ3QTM2bN3cYnmHFWsiXgFrKt8QEE). In addition to prior authentication and authorization functionality, this new Sign in with Google library also offers an improved user experience that increases data sharing transparency and decreases sign-in friction.
>
> Please migrate to the new Google Identity Services by following the guide for [authentication](https://notifications.google.com/g/p/APdRdFzSt791Adv8mCGIFSZ0mknvwTzeBFsJ1o30bAFoWdyP0oGQvd5ZIl4kBdxMRbEyH--xdZ5Dut58UnPFIh-xW5d3uobbm2i5efBmNg4f-fvXHG1g5BHkia7IYo6krCAZhdKQwtHXWLiSuYekaPPsCPFQ0owEOuM2IBHTy-UY4F9k345jGy36b9Ha3XcanG8Omg8FeWw9NWu0fwt_NYrPHLh1j3LCPuUo7kX1yH0anTZCdumSbufmpRL0QPGj6I-AfMf8qjYbI83QTRz6f90LZg). If you have migration-specific feedback to share, send an email to [gis-migration-feedback@google.com](mailto:gis-migration-feedback@google.com).

We're currently using https://www.npmjs.com/package/react-google-login, but it looks like they're not going to do the upgrade. [Someone mentioned](https://github.com/anthonyjgrove/react-google-login/issues/547#issuecomment-1327621308) that they moved to https://github.com/MomenSherif/react-oauth, which looks ok to me.

**Comment by anthonywittig** [comment]
Let's add a log out button in the top right nav.

**Comment by Thryphore** [comment]
https://github.com/anthonywittig/mLock/pull/59
