### ISSUE TITLE
Device's Online Status

### ISSUE THREAD

**Issue by anthonywittig** [anthonywittig/mLock#5]
I think we should change the text in the `Online` column to `On` and `Off`. Thoughts?

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/12345527/187060375-887274ee-0c1e-4759-9398-aea6cfb5ead6.png">

**Comment by Thryphore** [comment]
I feel like the wording is weird either way but it's better with on and off

**Comment by anthonywittig** [comment]
Could you try using the "Light" style on the non-offline badges too? I think it might make the spacing between the on/off badges look better (in the screenshot below the offline looks taller/wider because of the border):

<img width="108" alt="image" src="https://user-images.githubusercontent.com/12345527/187346241-2e449001-7bc0-4048-a3b4-a12f5fd858f0.png">

**Comment by anthonywittig** [comment]
What if we called the column `Reachability` and left the values as `Online`/`Offline` - thoughts?

**Comment by anthonywittig** [comment]
I'm changing my mind on this. I think we should kill the column and move the online/offline status back into the `status` column. We should display nothing if it's online, and show the red badge as the first thing in the list when it's offline.

**Comment by anthonywittig** [comment]
Done
