### ISSUE TITLE
Format the device errors

### ISSUE THREAD

**Issue by anthonywittig** [anthonywittig/mLock#52]
<img width="685" alt="image" src="https://user-images.githubusercontent.com/12345527/233228315-f453156b-0cd2-4b45-b4fb-d77b552c27de.png">

The "Not Responding (for code 2512)Not Responding (for code 4622)" should be two additional list group items.

**Comment by anthonywittig** [comment]
<img width="530" alt="image" src="https://user-images.githubusercontent.com/12345527/233251774-33b7f631-9dbd-45ec-9f03-305cab9c232d.png">

**Comment by Thryphore** [comment]
https://github.com/anthonywittig/mLock/pull/58
