### ISSUE TITLE
Unit Detail Page Improvements

### ISSUE THREAD

**Issue by anthonywittig** [anthonywittig/mLock#54]
1. Make the items in `Devices` links to the device.
2. (other items removed as they no longer make sense)

<img width="911" alt="image" src="https://user-images.githubusercontent.com/12345527/233763197-63798f07-795e-4d34-8249-d0dfcd7d1c08.png">

**Comment by Thryphore** [comment]
https://github.com/anthonywittig/mLock/pull/60
