### ISSUE TITLE
Lock Code Sorting

### ISSUE THREAD

**Issue by anthonywittig** [anthonywittig/mLock#56]
Now that we're creating reservations for codes that are in the distant future, we'd like to reorder the codes:

1. Enabled codes - sorted by enable at ascending (oldest to newest)
1. Adding codes - sorted by enable at ascending
1. Scheduled codes - sorted by enable at ascending 
1. Completed codes - sorted by **disable at descending**

**Comment by Thryphore** [comment]
https://github.com/anthonywittig/mLock/pull/57

**Comment by anthonywittig** [comment]
Ok, there was some miscommunication on this one, here's what we want:

1. Enabled codes - sorted by enable at descending (going backwards in time) - this is currently doing this, so no changes needed.
1. Adding codes - sorted by enable at descending (going backwards in time)
1. Removing codes - sorted by enable at descending (going backwards in time)
1. Scheduled codes - sorted by enable at ascending (going forward in time)
1. Completed codes - sorted by disable at ascending (going forward in time)

**Comment by anthonywittig** [comment]
Correction :) 

5. Completed codes - sorted by disable at descending (going backwards in time)

**Comment by Thryphore** [comment]
https://github.com/anthonywittig/mLock/pull/63
