### ISSUE TITLE
Add a "Reboot Controller" button to the device detail pages.

### ISSUE THREAD

**Issue by anthonywittig** [anthonywittig/mLock#68]
Not exactly sure where to put this... maybe add a row to the "details" for the "Controller ID" (`entity.controllerId`) with a button for rebooting the controller, like:

<img width="559" alt="image" src="https://github.com/anthonywittig/mLock/assets/12345527/eb25435e-b7b3-4e81-8089-1010bfbb2f87">

[Docs](https://react-bootstrap.netlify.app/docs/forms/input-group#button-addons)

When the button is clicked we should disable it so that they don't hit it a bunch of times. We don't need to reenable it, we can just wait for the user to reload the page for that to happen.

When the button is pushed you should do a POST `/devices/{ID}/reboot-controller/`.

**Comment by Thryphore** [comment]
https://github.com/anthonywittig/mLock/pull/72
