### ISSUE TITLE
Device list table breaks when viewed on a medium sized screen.

### ISSUE THREAD

**Issue by anthonywittig** [anthonywittig/mLock#9]
The table looks good when viewed on a small or large screen, but not so good in the middle (the content breaks out of the table). We might have this issue on other pages too.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/12345527/188053432-b357e1bf-bfb6-4967-96d5-f06d444b5e0e.png">

**Comment by Thryphore** [comment]
It breaks at a width of 1199, meaning you would need a 360p monitor to have that experience. Is it that big of a deal?

**Comment by anthonywittig** [comment]
The question might be, how did I discover this if I don't have a 360p monitor. 🤔 

I'm worried about our mobile (in landscape) and tablet users. I keep telling them to get bigger or smaller screens but they refuse to listen!

**Comment by anthonywittig** [comment]
Might help - https://react-bootstrap.github.io/components/table/
